import type { Member } from '@/types/entities'

const asset = (filename: string) => new URL(`../assets/${filename}`, import.meta.url).href

const skillsFrom = (input: string): string[] => input
  .split(/[,，、/\\]|\s+/)
  .map(skill => skill.trim())
  .filter(Boolean)

export const MOCK_MEMBERS: Member[] = [
  {
    id: 'member-tangmingdi',
    name: '唐明迪',
    role: '后端 / 模型训练',
    avatar: asset('tangmingdi.png'),
    bio: '擅长基于 SpringBoot 的服务化架构与无监督视觉模型训练，是俱乐部后端课程与 AI 实践的负责人之一。',
    skills: skillsFrom('SpringBoot, 无监督视觉模型, 计算机视觉, DevOps'),
    grade: '2023级',
    major: '软件工程',
    projectCount: 5,
    github: 'https://github.com/Arisgod1',
    joinDate: '2022-09-01',
    isActive: true
  },
  {
    id: 'member-dengyiming',
    name: '邓亦明',
    role: '深度学习',
    avatar: asset('dengyiming.png'),
    bio: '专注于大模型与算法工程，负责俱乐部的 AI 方向研讨与算力资源调度。',
    skills: skillsFrom('大模型, 深度学习, 模型调优'),
    grade: '2023级',
    major: '人工智能',
    projectCount: 4,
    github: 'https://github.com/dymgithub',
    joinDate: '2022-09-01',
    isActive: true
  },
  {
    id: 'member-liujingwen',
    name: '刘静雯',
    role: '前端开发',
    avatar: asset('liujingwen.png'),
    bio: '主攻 Node.js 与微信小程序生态，带领成员完成多端协同的小程序实战。',
    skills: skillsFrom('Node.js, 微信小程序, 前端工程化'),
    grade: '2023级',
    major: '软件工程',
    projectCount: 3,
    github: 'https://github.com/ywlbywl',
    joinDate: '2023-09-01',
    isActive: true
  },
  {
    id: 'member-zhencheng',
    name: '甄诚',
    role: 'Web开发 / 图形学',
    avatar: asset('zhencheng.png'),
    bio: '拥有 Vue 与工程仿真计算经验，擅长把复杂图形需求拆解为可复用组件。',
    skills: skillsFrom('Vue, 图形学, 工程仿真'),
    grade: '2023级',
    major: '数字媒体技术',
    projectCount: 4,
    github: 'https://github.com/Hi-Zachary',
    joinDate: '2023-09-01',
    isActive: true
  },
  {
    id: 'member-zhanghonghao',
    name: '张鸿昊',
    role: '后端开发',
    avatar: asset('zhanghonghao.png'),
    bio: '精通 Java 技术栈，擅长基于 SpringBoot 构建高并发服务，也是 Netty 与 Elasticsearch 的布道者。',
    skills: skillsFrom('Java, SpringBoot, SSM, Maven, MySQL, Redis, Netty, WebSocket, Elasticsearch'),
    grade: '2024级',
    major: '软件工程',
    projectCount: 6,
    github: 'https://github.com/zhh293',
    joinDate: '2024-09-01',
    isActive: true
  },
  {
    id: 'member-renchengda',
    name: '任诚达',
    role: '后端开发',
    avatar: asset('renchengda.png'),
    bio: '跨界于 Java Web、Python Web 以及 3D 内容创作，能够把课程项目延伸到虚拟空间。',
    skills: skillsFrom('Java Web, Python Web, Blender, Unity'),
    grade: '2024级',
    major: '软件工程',
    projectCount: 5,
    github: 'https://github.com/enderrcd',
    joinDate: '2024-09-01',
    isActive: true
  },
  {
    id: 'member-cairuihan',
    name: '蔡瑞含',
    role: '后端开发',
    avatar: asset('cairuihan.png'),
    bio: '使用 Python 与 Go 进行服务端开发，辅以 Fiber 等轻量级框架输出高性能 API。',
    skills: skillsFrom('Python, Go, Fiber'),
    grade: '2024级',
    major: '软件工程',
    projectCount: 4,
    github: 'https://github.com/MrCarfield',
    joinDate: '2022-09-01',
    isActive: true
  },
  {
    id: 'member-mayuha',
    name: '马玉灏',
    role: '后端开发',
    avatar: asset('mayuying.png'),
    bio: '专注 Go 语言与云端服务，善于用简洁的工程化方案支撑业务成长。',
    skills: skillsFrom('Golang, 微服务, DevOps'),
    grade: '2024级',
    major: '信息工程',
    projectCount: 3,
    github: 'https://github.com/yinxiangpingfan',
    joinDate: '2022-09-01',
    isActive: true
  },
  {
    id: 'member-maxingrui',
    name: '马鑫蕊',
    role: '前端开发',
    avatar: asset('maxingrui.png'),
    bio: '负责 Vue3 课程体系建设，亦参与 AI 产品孵化，常以开源形式分享实战经验。',
    skills: skillsFrom('Vue3, Node.js, PyTorch'),
    grade: '2024级',
    major: '软件工程',
    projectCount: 6,
    github: 'https://github.com/IHIRINA',
    joinDate: '2024-09-01',
    isActive: true
  },
  {
    id: 'member-wangmingfu',
    name: '王明富',
    role: '前端开发',
    avatar: asset('wangmingfu.png'),
    bio: '热爱移动端体验，使用 Android Studio 与 Flutter 打造多端一致的交互。',
    skills: skillsFrom('Android Studio, Flutter, 移动端 UI'),
    grade: '2024级',
    major: '软件工程',
    projectCount: 4,
    github: 'https://github.com/MF33006',
    joinDate: '2023-09-01',
    isActive: true
  },
  {
    id: 'member-wangyida',
    name: '王毅达',
    role: 'Godot 独立游戏开发',
    avatar: asset('wangyida.png'),
    bio: '使用 C# 与 Godot 引擎进行独立游戏创作，负责俱乐部的互动多媒体课程。',
    skills: skillsFrom('C#, Godot, 游戏设计'),
    grade: '2024级',
    major: '数字媒体',
    projectCount: 3,
    github: 'https://github.com/ksyou233',
    joinDate: '2024-09-01',
    isActive: true
  },
  {
    id: 'member-sunchangxiang',
    name: '孙常翔',
    role: '客户端开发',
    avatar: asset('sunchangxiang.png'),
    bio: '聚焦 Android 与 Python，负责客户端课程与跨端工具链建设。',
    skills: skillsFrom('Android Studio, Python, 客户端工程'),
    grade: '2024级',
    major: '计算机科学',
    projectCount: 4,
    github: 'https://github.com/CHANCE719',
    joinDate: '2022-09-01',
    isActive: true
  },
  {
    id: 'member-zhaoshuyang',
    name: '赵舒阳',
    role: '前后端开发',
    avatar: asset('zhaoshuyang.png'),
    bio: '在 Vue 与 Java 双栈均有经验，负责 AI 推荐项目的产品与技术统筹。',
    skills: skillsFrom('Vue, Java, 全栈开发'),
    grade: '2024级',
    major: '软件工程',
    projectCount: 5,
    github: 'https://github.com/qin-net',
    joinDate: '2024-09-01',
    isActive: true
  },
  {
    id: 'member-sichenfei',
    name: '司辰飞',
    role: '后端开发',
    avatar: asset('sichenfei.png'),
    bio: '算法背景扎实，擅长 C++ / Java 混合开发，负责进阶算法与后端性能优化分享。',
    skills: skillsFrom('算法, C++, Java'),
    grade: '2024级',
    major: '计算机科学',
    projectCount: 4,
    github: 'https://github.com/stars569',
    joinDate: '2022-09-01',
    isActive: true
  },
  {
    id: 'member-baoyunye',
    name: '包昀烨',
    role: '前端开发',
    avatar: asset('baoyunye.png'),
    bio: '兼具 Python 与 Java 背景，为前端同学提供服务器端支撑，是多栈协作的纽带。',
    skills: skillsFrom('Python, Java, 前端工程化'),
    grade: '2024级',
    major: '软件工程',
    projectCount: 3,
    github: 'https://github.com/YYiee',
    joinDate: '2023-09-01',
    isActive: true
  }
]
