import type { Member } from '@/types/entities'

export const MOCK_MEMBERS: Member[] = [
   {
    id: '1',
    name: '唐明迪',
    role: '后端，模型训练',
    avatar: '',
    bio: '基于SpringBoot的后端搭建，无监督视觉模型的训练与使用。',
    skills: ['SpringBoot', '视觉模型', '机器学习'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '2',
    name: '邓亦明',
    role: '深度学习',
    avatar: '',
    bio: '大模型方向研究。',
    skills: ['深度学习', '大模型'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '3',
    name: '刘静雯',
    role: '前端开发',
    avatar: '',
    bio: 'Node.js，微信小程序开发。',
    skills: ['Node.js', '微信小程序'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '4',
    name: '甄诚',
    role: 'Web开发，图形学',
    avatar: '',
    bio: 'Vue 开发，工程仿真计算。',
    skills: ['Vue', '工程仿真'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '5',
    name: '张鸿昊',
    role: '后端开发',
    avatar: '',
    bio: 'Java、SpringBoot、SSM、Maven、MySQL、Redis、Netty、WebSocket、Elasticsearch 等开发经验。',
    skills: ['Java', 'SpringBoot', 'MySQL', 'Redis', 'Netty', 'Elasticsearch'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '6',
    name: '任诚达',
    role: '后端开发',
    avatar: '',
    bio: 'Java Web、Python Web、Blender建模、Unity开发。',
    skills: ['JavaWeb', 'PythonWeb', 'Blender', 'Unity'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '7',
    name: '蔡瑞含',
    role: '后端开发',
    avatar: '',
    bio: 'Python、Go、Fiber Web 框架开发。',
    skills: ['Python', 'Go', 'Fiber'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '8',
    name: '马玉灏',
    role: '后端开发',
    avatar: '',
    bio: 'Golang 后端开发。',
    skills: ['Golang'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '9',
    name: '马鑫蕊',
    role: '前端开发',
    avatar: '',
    bio: 'Vue3、Node.js、PyTorch 等技术栈。',
    skills: ['Vue3', 'Node.js', 'PyTorch'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '10',
    name: '王明富',
    role: '前端开发',
    avatar: '',
    bio: 'Android Studio 开发，Flutter 跨平台开发。',
    skills: ['Android', 'Flutter'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '11',
    name: '王毅达',
    role: 'Godot独立游戏开发',
    avatar: '',
    bio: '使用 C# 进行 Godot 独立游戏开发。',
    skills: ['C#', 'Godot'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '12',
    name: '孙常翔',
    role: '客户端开发',
    avatar: '',
    bio: 'Android Studio 客户端开发，熟悉 Python。',
    skills: ['Android', 'Python'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '13',
    name: '赵舒阳',
    role: '前后端开发',
    avatar: '',
    bio: 'Vue 全栈开发，Java 后端。',
    skills: ['Vue', 'Java'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '14',
    name: '司辰飞',
    role: '后端开发',
    avatar: '',
    bio: '算法、C++、Java 等技术方向。',
    skills: ['C++', 'Java', '算法'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  },
  {
    id: '15',
    name: '包昀烨',
    role: '前端开发',
    avatar: '',
    bio: 'Python、Java 开发经验。',
    skills: ['Python', 'Java'],
    grade: '2020级',
    major: '软件工程',
    projectCount: 0,
    email: '',
    joinDate: '',
    isActive: true
  }
]
