import { type Project, Category, Status } from '@/types/entities'

const asset = (filename: string) => new URL(`../assets/${filename}`, import.meta.url).href

export const MOCK_PROJECTS: Project[] = [
  {
    id: 101,
    title: 'RACE 智慧外卖平台',
    name: 'race',
    shortDescription: '传统外卖业务的全栈重构',
    description: '效仿传统外卖平台，覆盖订单、用户、管理、支付、配送与数据分析等完整模块，帮助新人将后端知识串联成体系。',
    summary: '聚焦分布式订单链路与多角色权限，结合 Redis 做高并发缓存演练。',
    category: Category.Development,
    status: Status.InProgress,
    techStack: ['SpringBoot', 'MySQL', 'Redis'],
    contributors: ['张鸿昊'],
    repositoryUrl: 'https://gitee.com/nine-twenty-eight-nineteen/race',
    githubUrl: 'https://gitee.com/nine-twenty-eight-nineteen/race',
    documentation: 'https://gitee.com/nine-twenty-eight-nineteen/race',
    startDate: '2024-02-20',
    progress: 82,
    featured: true,
    teamSize: 3,
    likes: 56,
    views: 640,
    imageUrl: asset('richang1.png'),
    images: [asset('richang1.png'), asset('richang2.png')]
  },
  {
    id: 102,
    title: 'Netty RPC & 聊天框架',
    name: 'RPC',
    shortDescription: '基于 Netty 的即时通信与 RPC 引擎',
    description: '构建轻量级聊天室与 RPC 基础设施，打破传统 BIO 模式，实现更高效、稳定的网络通信。',
    summary: '以 Netty 为底座演练序列化、连接管理与远程调用，便于服务化课程实践。',
    category: Category.Development,
    status: Status.Planning,
    techStack: ['Netty', 'Java'],
    contributors: ['张鸿昊'],
    repositoryUrl: 'https://github.com/zhh293/-RPC-',
    githubUrl: 'https://github.com/zhh293/-RPC-',
    documentation: 'https://github.com/zhh293/-RPC-#readme',
    startDate: '2024-03-10',
    progress: 55,
    featured: false,
    teamSize: 2,
    likes: 24,
    views: 310,
    imageUrl: asset('richang3.png'),
    images: [asset('richang3.png')]
  },
  {
    id: 103,
    title: 'JobSense 面试智能体（后端）',
    name: 'jobsensebackpart',
    shortDescription: '支持语音/视频/文本的 AI 面试评测工具',
    description: '构建可以处理语音、视频与文本的 AI 面试助手后端，提供实时评测、面试流程管理以及多模态反馈。',
    summary: '结合 Spring AI、WebSocket 与 Redis 保障多会话实时性，服务校内 AI 创业项目。',
    category: Category.Research,
    status: Status.InProgress,
    techStack: ['SpringBoot', 'Spring AI', 'PostgreSQL', 'Redis', 'WebSocket'],
    contributors: ['张鸿昊'],
    repositoryUrl: 'https://github.com/Arisgod1/jobsensebackpart',
    githubUrl: 'https://github.com/Arisgod1/jobsensebackpart',
    startDate: '2024-04-05',
    progress: 68,
    featured: true,
    teamSize: 4,
    likes: 73,
    views: 820,
    imageUrl: asset('richang4.png'),
    images: [asset('richang4.png'), asset('richang2.png')]
  },
  {
    id: 104,
    title: 'AI 电子设备分析平台',
    name: 'tech-recomendation',
    shortDescription: '利用 AI 做设备评测与推荐',
    description: '通过 AI 对电子设备参数进行解析，为用户匹配合适的硬件，兼顾内容生产与交互设计。',
    summary: '结合 Python/Flask 推理与前端展示，沉淀一套可复用的智能推荐模板。',
    category: Category.Development,
    status: Status.InProgress,
    techStack: ['HTML', 'CSS', 'JavaScript', 'Python', 'Flask'],
    contributors: ['赵舒阳', '王明富'],
    repositoryUrl: 'https://github.com/qin-net/tech-recomendation',
    githubUrl: 'https://github.com/qin-net/tech-recomendation',
    startDate: '2024-03-25',
    progress: 64,
    featured: false,
    teamSize: 3,
    likes: 41,
    views: 520,
    imageUrl: asset('richang1.png'),
    images: [asset('richang1.png'), asset('richang3.png')]
  },
  {
    id: 105,
    title: '音艺智创 · 元宇宙音乐教育平台',
    name: 'MusicShowCenter',
    shortDescription: '面向音乐教学的沉浸式 Web 平台',
    description: '构建基于 Web 的元宇宙音乐学习体验，整合课程、互动教具与虚拟舞台。',
    summary: '提供在线乐理课堂、作品展厅与社群互动，支持多终端接入。',
    category: Category.Education,
    status: Status.Completed,
    techStack: ['HTML', 'CSS', 'JavaScript', 'Bootstrap 5', 'Flask', 'MySQL'],
    contributors: ['任诚达'],
    repositoryUrl: 'https://github.com/enderrcd/MusicShowCenter',
    githubUrl: 'https://github.com/enderrcd/MusicShowCenter',
    documentation: 'https://github.com/enderrcd/MusicShowCenter#readme',
    startDate: '2023-12-01',
    endDate: '2024-06-30',
    progress: 100,
    featured: true,
    teamSize: 4,
    likes: 88,
    views: 910,
    imageUrl: asset('richang2.png'),
    images: [asset('richang2.png')]
  },
  {
    id: 106,
    title: '今日计划 · AI 生活助理',
    name: 'race-plan',
    shortDescription: '多模态输入的个人日程规划工具',
    description: '结合语音、文字与图片输入，使用 AI 生成每日计划清单，帮助同学规划自律生活。',
    summary: '基于 Vue3 与 Element Plus 打造跨端体验，是新人熟悉前端生态的练手项目。',
    category: Category.Development,
    status: Status.Planning,
    techStack: ['Vue3', 'Element-Plus'],
    contributors: ['马鑫蕊'],
    repositoryUrl: 'https://github.com/IHIRINA/race/tree/my-vue',
    githubUrl: 'https://github.com/IHIRINA/race/tree/my-vue',
    startDate: '2024-05-18',
    progress: 48,
    featured: false,
    teamSize: 2,
    likes: 39,
    views: 430,
    imageUrl: asset('richang3.png'),
    images: [asset('richang3.png'), asset('richang4.png')]
  },
  {
    id: 107,
    title: 'Stick On 生活磁贴',
    name: 'Stick On',
    shortDescription: '用磁贴记录生活、用 AI 召回记忆',
    description: '打造轻量级生活记录工具，将日常灵感整理成磁贴，用 AI 回顾故事。',
    summary: '融合 Vue3、Vite、Pinia 与 Capacitor，探索跨平台发行与用户体验。',
    category: Category.Development,
    status: Status.InProgress,
    techStack: ['Vue3', 'Vite', 'Pinia', 'Element-Plus', 'TypeScript', 'Capacitor'],
    contributors: ['马鑫蕊'],
    repositoryUrl: 'https://github.com/IHIRINA/vibe',
    githubUrl: 'https://github.com/IHIRINA/vibe',
    startDate: '2024-04-28',
    progress: 70,
    featured: true,
    teamSize: 3,
    likes: 65,
    views: 760,
    imageUrl: asset('richang4.png'),
    images: [asset('richang4.png'), asset('richang1.png')]
  },
  {
    id: 108,
    title: 'antiFraud 反诈助手',
    name: 'antiFraud',
    shortDescription: '训练 AI 识别诈骗话术的移动应用',
    description: '自建数据集训练模型，实时识别和提示高风险对话，帮助用户规避电信诈骗。',
    summary: '结合 Vue3 前端、Go 服务与 PyTorch 推理，验证端云联动的反诈方案。',
    category: Category.Research,
    status: Status.InProgress,
    techStack: ['Vue3', 'Go', 'PyTorch'],
    contributors: ['马鑫蕊'],
    repositoryUrl: 'https://github.com/IHIRINA/antiFraud',
    githubUrl: 'https://github.com/IHIRINA/antiFraud',
    startDate: '2024-05-05',
    progress: 58,
    featured: false,
    teamSize: 3,
    likes: 47,
    views: 540,
    imageUrl: asset('richang2.png'),
    images: [asset('richang2.png')]
  }
]
