import { type Project, Category, Status } from '@/types/entities'

export const MOCK_PROJECTS: Project[] = [
  {
    id: 1,
    name: 'blockchain_website',
    description: '区块链组官方网站，基于Vue3构建的现代响应式Web站点',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Vue3', 'TypeScript', 'Vite'],
    imageUrl: 'https://picsum.photos/id/11/800/600',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2025-02-15'),
    featured: true,
    progress: 100
  },
  {
    id: 2,
    name: 'zkp_rkp_go',
    description: 'ZKP零知识验证登录系统后端，使用Go语言重构，提供安全的身份验证方案',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Go', 'Gin', 'GORM'],
    imageUrl: 'https://picsum.photos/id/12/800/600',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2025-03-15'),
    featured: true,
    progress: 100
  },
  {
    id: 3,
    name: 'Whack-a-Mole',
    description: '基于EasyX图形库的打地鼠游戏，经典小游戏开发实践',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['C++', 'EasyX'],
    imageUrl: 'https://picsum.photos/id/13/800/600',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2025-04-15'),
    featured: true,
    progress: 100
  },
  {
    id: 4,
    name: 'ACM_Summary',
    description: 'ACM竞赛能力分析平台，追踪和可视化竞赛成绩与能力成长',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['TypeScript', 'React', 'Node.js'],
    imageUrl: 'https://picsum.photos/id/14/800/600',
    startDate: new Date('2024-05-01'),
    endDate: new Date('2025-05-15'),
    featured: true,
    progress: 100
  },
  {
    id: 5,
    name: 'ChainTask',
    description: '基于区块链技术的去中心化任务平台，任何人都可以发布任务并悬赏代币，任何人都可以接单赚取收益',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Python', 'Web3', 'Solidity'],
    imageUrl: 'https://picsum.photos/id/15/800/600',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2025-06-15'),
    featured: true,
    progress: 100
  },
  {
    id: 6,
    name: 'BolckChainBackEnd',
    description: '区块链后端服务系统，支持区块管理、交易处理和智能合约交互',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Java', 'Spring Boot', 'MySQL'],
    imageUrl: 'https://picsum.photos/id/16/800/600',
    startDate: new Date('2024-07-01'),
    endDate: new Date('2025-01-15'),
    featured: false,
    progress: 100
  },
  {
    id: 7,
    name: 'code-reviewer-agent',
    description: 'AI代码审查Agent，自动分析代码变更、检测问题并提供改进建议',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Go', 'LLM', 'AST'],
    imageUrl: 'https://picsum.photos/id/17/800/600',
    startDate: new Date('2024-08-01'),
    endDate: new Date('2025-02-15'),
    featured: false,
    progress: 100
  },
  {
    id: 8,
    name: 'BlockChain_GIt',
    description: '大连理工大学区块链组Git版本控制例会仓库，2025-2026年例会内容集合',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Python', 'Git', 'Markdown'],
    imageUrl: 'https://picsum.photos/id/18/800/600',
    startDate: new Date('2024-09-01'),
    endDate: new Date('2025-03-15'),
    featured: false,
    progress: 100
  },
  {
    id: 9,
    name: 'RepoNecromancer',
    description: 'GitHub尸检分析工具，通过AI自动分析GitHub仓库的代码质量、提交历史和项目健康度',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Go', 'OpenAI', 'GitHub API'],
    imageUrl: 'https://picsum.photos/id/19/800/600',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2025-04-15'),
    featured: false,
    progress: 100
  },
  {
    id: 10,
    name: 'GateWayTemplate',
    description: '企业级网关模板实现，涵盖认证、限流、路由、监控等核心功能',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Java', 'Spring Cloud', 'Redis'],
    imageUrl: 'https://picsum.photos/id/20/800/600',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2025-05-15'),
    featured: false,
    progress: 100
  },
  {
    id: 11,
    name: 'CLI-Genie',
    description: '基于Go的命令行助手，将中文需求转换为可执行的Linux复合命令，支持上下文记忆和风险评估',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Go', 'LLM', 'CLI'],
    imageUrl: 'https://picsum.photos/id/21/800/600',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2025-06-15'),
    featured: false,
    progress: 100
  },
  {
    id: 12,
    name: '-RPC-',
    description: '轻量级聊天室和RPC框架实现，支持服务发现和远程过程调用',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Java', 'Netty', 'ZooKeeper'],
    imageUrl: 'https://picsum.photos/id/22/800/600',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2025-01-15'),
    featured: false,
    progress: 100
  },
  {
    id: 13,
    name: 'aggo',
    description: '基于Go和CloudWeGo Eino框架构建的企业级AI Agent框架，支持多场景业务定制',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Go', 'Eino', 'CloudWeGo'],
    imageUrl: 'https://picsum.photos/id/23/800/600',
    startDate: new Date('2024-05-01'),
    endDate: new Date('2025-02-15'),
    featured: false,
    progress: 100
  },
  {
    id: 14,
    name: 'StickBasicCloud',
    description: '将轻贴系统重构为微服务架构，支持高并发和分布式部署',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Java', 'Spring Cloud', 'Docker'],
    imageUrl: 'https://picsum.photos/id/24/800/600',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2025-03-15'),
    featured: false,
    progress: 100
  },
  {
    id: 15,
    name: 'compus-second-hand',
    description: '基于Go微服务架构的校园二手交易平台，使用go-micro、etcd、MySQL、Redis等技术栈',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Go', 'go-micro', 'Redis'],
    imageUrl: 'https://picsum.photos/id/25/800/600',
    startDate: new Date('2024-07-01'),
    endDate: new Date('2025-04-15'),
    featured: false,
    progress: 100
  },
  {
    id: 16,
    name: 'jobsensefrontpart',
    description: '灵录师前端，AI面试评测工具，支持语音、视频、文本多模态分析，评估面试表现并提供改进建议',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Vue3', 'WebRTC', 'TensorFlow.js'],
    imageUrl: 'https://picsum.photos/id/26/800/600',
    startDate: new Date('2024-08-01'),
    endDate: new Date('2025-05-15'),
    featured: false,
    progress: 100
  },
  {
    id: 17,
    name: 'jobsensebackpart',
    description: '灵录师后端，AI面试智能体的后端部分，通过表情识别、语音情感分析、语义理解评估面试表现',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Java', 'Spring Boot', 'Kafka'],
    imageUrl: 'https://picsum.photos/id/27/800/600',
    startDate: new Date('2024-09-01'),
    endDate: new Date('2025-06-15'),
    featured: false,
    progress: 100
  },
  {
    id: 19,
    name: 'AI-Picture-in-Picture',
    description: 'AI互动应用，实现图像前景背景分离与融合，支持创意图片合成',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['JavaScript', 'TensorFlow.js', 'Canvas'],
    imageUrl: 'https://picsum.photos/id/29/800/600',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2025-02-15'),
    featured: false,
    progress: 100
  },
  {
    id: 20,
    name: 'school-runing-dut',
    description: '大连理工大学开发区校区校园跑一键刷圈工具，自动记录跑步数据',
    category: Category.Development,
    status: Status.Completed,
    techStack: ['Python', 'Flask', '微信小程序'],
    imageUrl: 'https://picsum.photos/id/30/800/600',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2025-03-15'),
    featured: false,
    progress: 100
  }
]
